"""empty message

Revision ID: 8ed32bba5e04
Revises: 44c052446c78
Create Date: 2026-07-17 08:09:28.749776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed32bba5e04'
down_revision = '44c052446c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_character_character_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])
        
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_character_character_id_fkey'), 'characters', ['character_id'], ['id'])

    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('characters_pkey'))
    )
    op.drop_table('character')
    # ### end Alembic commands ###
